version: '3.8'

services:

    elasticsearch:
        container_name: stack_elasticsearch_${ELASTICSEARCH_VERSION:-7.3.2}
        build:
            context: custom/elasticsearch
            network: host
            args:
                - ELASTICSEARCH_VERSION=${ELASTICSEARCH_VERSION:-7.3.2}
        image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION:-7.3.2}
        env_file: .env_elasticsearch_${ENV_FILE_VERSION:-7}
        environment:
            - node.name="es-stack-1"
        ports:
            - "${ELASTICSEARCH_PORT:-9200}:9200"
        networks:
            - stack
        volumes:
            - type: bind
              source: ../snapshots
              target: /snapshots

    kibana:
        container_name: stack_kibana_${KIBANA_VERSION:-7.3.2}
        image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION:-7.3.2}
        env_file: .env_kibana_${ENV_FILE_VERSION:-7}
        environment:
            - ELASTICSEARCH_HOSTS="http://elasticsearch:9200"
        ports:
            - "${KIBANA_PORT:-5601}:5601"
        depends_on:
            - elasticsearch
        networks:
            - stack

    logstash-data-loader:
        container_name: stack_logstash-data-loader_${LOGSTASH_VERSION:-7.3.2}
        build:
            context: custom/logstash-data-loader
            network: host
            args:
                - LOGSTASH_VERSION=${LOGSTASH_VERSION:-7.3.2}
        env_file: .env_logstash-data-loader_${ENV_FILE_VERSION:-7}
        ports:
            - "${LOGSTASH_PORT:-9600}:9600"
        depends_on:
            - elasticsearch
        networks:
            - stack
        volumes:
            - ../data:/data


    es-loader:
        container_name: stack_es-loader_${ELASTICSEARCH_VERSION:-7.3.2}
        build:
            context: custom/es-loader
            network: host
        depends_on:
            - elasticsearch
        networks:
            - stack
        volumes:
            - ../index-templates:/index-templates
            - ../bin:/stack-bin
        command: bash /stack-bin/init.sh /index-templates elasticsearch

networks:
    stack:
