version: '3'

services:

    kibana:
        image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION:-7.3.2}
        environment:
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        ports:
            - "5601:5601"
        networks:
            - stack

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION:-7.3.2}
        environment:
            node.name: es-stack-1
            cluster.initial_master_nodes: es-stack-1
        ports:
            - "9200:9200"
        networks:
            - stack

networks:
    stack:
