version: '3.8'

services:

    kibana:
        image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION:-7.3.2}
        env_file: .env_kibana_${ENV_FILE_VERSION:-7}
        environment:
            - ELASTICSEARCH_HOSTS="http://elasticsearch:9200"
        ports:
            - "${KIBANA_PORT:-5601}:5601"
        networks:
            - stack

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION:-7.3.2}
        env_file: .env_elasticsearch_${ENV_FILE_VERSION:-7}
        environment:
            - node.name="es-stack-1"
        ports:
            - "${ELASTICSEARCH_PORT:-9200}:9200"
        networks:
            - stack

    logstash:
        build:
            context: custom/logstash
            network: host
        ports:
            - "${LOGSTASH_PORT:-9600}:9600"
        networks:
            - stack

networks:
    stack:
